version: "3.8"

services:
  nimbus2_checkpoint:
    image: statusim/nimbus-eth2:multiarch-$NIMBUS2_VERSION
    container_name: nimbus2_checkpoint
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      trustedNodeSync
      --network=/configs
      --data-dir=/consensus_data
      --trusted-node-url=$CHECKPOINT_SYNC_URL

  nimbus2:
    image: statusim/nimbus-eth2:multiarch-$NIMBUS2_VERSION
    container_name: nimbus2
    depends_on:
      nimbus2_checkpoint:
        condition: service_completed_successfully
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    network_mode: host
    command: >
      --network=/configs
      --data-dir=/consensus_data
      --bootstrap-file=/configs/bootnodes.txt
      --genesis-state=/configs/genesis.ssz
      --nat=extip:$EXTERNAL_IP
      --rest
      --rest-address='127.0.0.1'
      --rest-port=5052
