version: "3.8"

services:
  init-erigon:
    image: thorax/erigon:$ERIGON_VERSION
    container_name: init-erigon
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    command: >
      --datadir=/execution_data init /configs/genesis.json

  erigon:
    image: thorax/erigon:$ERIGON_VERSION
    container_name: erigon
    depends_on:
      - init-erigon
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --datadir=/execution_data
      --networkid=$LUKSO_MAINNET_NETWORK_ID
      --externalcl
      --miner.gaslimit=42000000
      --authrpc.jwtsecret=/configs/jwt.hex
      --snapshots=0
      --nat="extip:$EXTERNAL_IP"
      --http
      --http.addr="0.0.0.0"
      --http.api="erigon,engine"
      --http.vhosts="*"
      --authrpc.addr="0.0.0.0"
      --authrpc.port=8551
      --authrpc.vhosts="*"
      --bootnodes="$EXECUTION_BOOTSTRAP_NODE_1,$EXECUTION_BOOTSTRAP_NODE_2"
      --metrics
      --metrics.addr="0.0.0.0"
      --ethstats="${NODE_NAME}:${ETH_STATS_SECRET}@${ETH_STATS_ADDRESS}"
    # ports:
    #   - "30303:30303" # eth/66 peering
    #   - "30304:30304" # eth/67 peering
    #   - "9090:9090" # gRPC Connections
    #   - "42069:42069" # Snap sync (Bittorrent)
    #   - "6060:6060" # Metrics or Pprof
    #   - "8551:8551" # Engine API (JWT auth)
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"

  lighthouse:
    image: sigp/lighthouse:$LIGHTHOUSE_VERSION
    restart: unless-stopped
    depends_on:
      - geth
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
      - $CONFIGS_VOLUME/lighthouse/deploy_block.txt:/configs/shared/deploy_block.txt
    command:
      - lighthouse
      - --testnet-dir=/configs/shared
      - bn
      - --datadir=/consensus_data
      - --listen-address=0.0.0.0
      - --eth1
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --discovery-port=9000
      - --enable-private-discovery
      - --enr-address=$EXTERNAL_IP
      - --execution-jwt=/configs/jwt.hex
      - --execution-endpoint=http://localhost:8551
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --suggested-fee-recipient=$FEE_RECIPIENT
      - --boot-nodes=$CONSENSUS_BOOT_NODES
      - --slots-per-restore-point=32
    network_mode: host
