version: "3.8"

services:
  init-erigon:
    image: thorax/erigon:$ERIGON_VERSION
    container_name: init-erigon
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    command: >
      --datadir=/execution_data init /configs/genesis.json

  erigon:
    image: thorax/erigon:$ERIGON_VERSION
    container_name: erigon
    depends_on:
      - init-erigon
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --datadir=/execution_data
      --networkid=$LUKSO_NETWORK_ID
      --miner.gaslimit=42000000
      --authrpc.jwtsecret=/configs/jwt.hex
      --snapshots=0
      --nat="extip:$EXTERNAL_IP"
      --http
      --http.addr="0.0.0.0"
      --http.api="erigon,engine"
      --http.vhosts="*"
      --authrpc.addr="0.0.0.0"
      --authrpc.port=8551
      --authrpc.vhosts="*"
      --bootnodes="$EXECUTION_BOOTSTRAP_NODE_1,$EXECUTION_BOOTSTRAP_NODE_2"
      --metrics
      --metrics.addr="0.0.0.0"
      --ethstats="${NODE_NAME}:${ETH_STATS_SECRET}@${ETH_STATS_ADDRESS}"
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"

  teku:
    image: consensys/teku:$TEKU_VERSION
    container_name: teku
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --initial-state /configs/genesis.ssz
      --network /configs/config.yaml
      --data-path /consensus_data
      --p2p-discovery-bootnodes $CONSENSUS_BOOTSTRAP_NODE_1
      --ee-endpoint http://localhost:8551
      --ee-jwt-secret-file /configs/jwt.hex
      --validators-proposer-default-fee-recipient $FEE_RECIPIENT
      --p2p-interface 0.0.0.0
      --p2p-port 9000
      --p2p-peer-lower-bound 0
      --p2p-peer-upper-bound 250
      --p2p-subscribe-all-subnets-enabled
      --metrics-enabled
      --metrics-interface 0.0.0.0
      --rest-api-enabled
      --rest-api-host-allowlist=*
      --rest-api-interface 0.0.0.0
      --rest-api-cors-origins=*
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"
