version: "3.8"
services:

  init-geth:
    image: ethereum/client-go:$GETH_VERSION
    container_name: geth-init
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    command: >
      --datadir=/execution_data init /configs/genesis.json

  geth:
    image: ethereum/client-go:$GETH_VERSION
    container_name: geth
    depends_on:
      - init-geth
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --datadir=/execution_data
      --ws
      --ws.api "eth,net"
      --ws.addr 0.0.0.0
      --ws.origins "*"
      --http
      --http.api "eth,net"
      --http.addr "0.0.0.0"
      --http.corsdomain "*"
      --http.vhosts "*"
      --ipcdisable
      --authrpc.jwtsecret /configs/jwt.hex
      --datadir=/execution_data
      --bootnodes $EXECUTION_BOOTSTRAP_NODE_1
      --networkid $LUKSO_MAINNET_NETWORK_ID
      --verbosity $GETH_VERBOSITY
      --metrics
      --metrics.addr "0.0.0.0"
      --miner.gaslimit 42000000
      --miner.gasprice 4200000000
      --ethstats "${NODE_NAME}:${ETH_STATS_SECRET}@${ETH_STATS_ADDRESS}"
      --nat extip:$EXTERNAL_IP
     # Change/add your custom flags here:
     # https://geth.ethereum.org/docs/fundamentals/command-line-options
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"
  
  teku:
    image: consensys/teku:$TEKU_VERSION
    environment:
      - "JAVA_OPTS=-Xmx4g"
    container_name: teku
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    command: >
      --initial-state=https://checkpoints.testnet.lukso.network/eth/v2/debug/beacon/states/finalized
      --network=/configs/teku/config.yaml
      --data-path=/consensus_data
      --p2p-discovery-bootnodes=$CONSENSUS_BOOTSTRAP_NODE_1
      --ee-endpoint=http://localhost:8551
      --ee-jwt-secret-file=/configs/jwt.hex
      --validators-proposer-default-fee-recipient=$FEE_RECIPIENT
      --p2p-interface=0.0.0.0
      --p2p-advertised-ip=$EXTERNAL_IP
      --p2p-port=10000
      --p2p-peer-lower-bound=0
      --p2p-peer-upper-bound=250
      --p2p-subscribe-all-subnets-enabled
      --metrics-enabled
      --metrics-interface=0.0.0.0
      --rest-api-enabled
      --rest-api-host-allowlist=*
      --rest-api-interface=0.0.0.0
      --rest-api-cors-origins=*
      --log-destination=CONSOLE
    network_mode: host
    
  teku_validator:
    image: consensys/teku:$TEKU_VERSION
    container_name: teku_validator
    depends_on:
      teku:
        condition: service_started
      web3signer:
        condition: service_started
    volumes:
      - $KEYSTORES_VOLUME:/keystore
      - $VALIDATOR_DATA_VOLUME:/validator_data
      - $CONFIGS_VOLUME:/configs
    command:
      - validator-client
      - --beacon-node-api-endpoint=http://127.0.0.1:5051
      - --validator-keys=/keystore:/keystore
      - --data-path=/validator_data
      - --network=/configs/teku/config.yaml
      - --metrics-enabled
      - --metrics-port=8009
      - --validators-proposer-default-fee-recipient=$FEE_RECIPIENT
      - --validators-external-signer-url=http://127.0.0.1:9000
      - --validators-external-signer-public-keys=http://127.0.0.1:9000/api/v1/eth2/publicKeys
      - --log-destination=CONSOLE
  
  web3signer:
    image: consensys/web3signer:develop
    volumes:
      - $CONFIGS_VOLUME:/configs
      - $KEYSTORES_VOLUME:/keystore
      - $TMP_VOLUME:/tmp/secrets
    container_name: web3signer
    command: >
      eth2
      --slashing-protection-enabled=false
      --network=/configs/config.yaml
      --keystores-path=/keystore
      --keystores-password-file=/tmp/secrets/password.txt
    ports:
      - "9000:9000"
