version: "3.8"
services:

  init-geth:
    image: ethereum/client-go:$GETH_VERSION
    container_name: geth-init
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    command: >
      --datadir=/execution_data init /configs/genesis.json

  geth:
    image: ethereum/client-go:$GETH_VERSION
    container_name: geth
    depends_on:
      - init-geth
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --datadir=/execution_data
      --ws
      --ws.api "eth,net"
      --ws.addr 0.0.0.0
      --ws.origins "*"
      --http
      --http.api "eth,net"
      --http.addr "0.0.0.0"
      --http.corsdomain "*"
      --http.vhosts "*"
      --ipcdisable
      --authrpc.jwtsecret /configs/jwt.hex
      --datadir=/execution_data
      --bootnodes $EXECUTION_BOOTSTRAP_NODE_1
      --networkid $LUKSO_MAINNET_NETWORK_ID
      --verbosity $GETH_VERBOSITY
      --metrics
      --metrics.addr "0.0.0.0"
      --miner.gaslimit 42000000
      --miner.gasprice 4200000000
      --ethstats "${NODE_NAME}:${ETH_STATS_SECRET}@${ETH_STATS_ADDRESS}"
      --nat extip:$EXTERNAL_IP
     # Change/add your custom flags here:
     # https://geth.ethereum.org/docs/fundamentals/command-line-options
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"

  prysm:
    image: prysmaticlabs/prysm-beacon-chain:$PRYSM_BEACON_VERSION
    container_name: prysm
    depends_on:
      - geth
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --accept-terms-of-use
      --genesis-state=/configs/genesis.ssz
      --chain-config-file=/configs/config.yaml
      --datadir=/consensus_data
      --bootstrap-node $PRYSM_BOOTSTRAP_NODE
      --execution-endpoint=http://localhost:8551
      --jwt-secret=/configs/jwt.hex
      --suggested-fee-recipient $FEE_RECIPIENT
      --min-sync-peers=0
      --monitoring-host 0.0.0.0
      --grpc-gateway-host 0.0.0.0
      --rpc-host 0.0.0.0
      --verbosity $PRYSM_VERBOSITY
      --p2p-max-peers 250
      --subscribe-all-subnets
      --minimum-peers-per-subnet 0
      --contract-deployment-block 0
      --block-batch-limit 512
      --block-batch-limit-burst-factor 10
      --p2p-host-ip $EXTERNAL_IP
      --checkpoint-sync-url=https://checkpoints.testnet.lukso.network
     # Add your custom flags here.
     # Docs: https://docs.prylabs.network/docs/prysm-usage/parameters#beacon-node-flags
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"

  prysm_validator:
    image: prysmaticlabs/prysm-validator:v4.0.3
    container_name: prysm_validator
    depends_on:
      prysm:
        condition: service_started
      web3signer:
        condition: service_started
    volumes:
      - $KEYSTORES_VOLUME:/keystore
      - $VALIDATOR_DATA_VOLUME:/validator_data
      - $CONFIGS_VOLUME:/configs
      - $TMP_VOLUME:/tmp/secrets
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --accept-terms-of-use
      --datadir /validator_data
      --wallet-dir /keystore/prysm
      --wallet-password-file /tmp/secrets/password.txt
      --chain-config-file /configs/config.yaml
      --monitoring-host 0.0.0.0
      --grpc-gateway-host 0.0.0.0
      --rpc-host 0.0.0.0
      --suggested-fee-recipient $FEE_RECIPIENT
      --validators-external-signer-url=http://127.0.0.1:9000
      --validators-external-signer-public-keys=http://127.0.0.1:9000/api/v1/eth2/publicKeys
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"

  web3signer:
    image: consensys/web3signer:develop
    volumes:
      - $CONFIGS_VOLUME:/configs
      - $KEYSTORES_VOLUME:/keystore
      - $TMP_VOLUME:/tmp/secrets
    container_name: web3signer
    command: >
      eth2
      --slashing-protection-enabled=false
      --network=/configs/config.yaml
      --keystores-path=/keystore
      --keystores-password-file=/tmp/secrets/password.txt
    ports:
      - "9000:9000"
