version: "3.8"

services:
  nethermind:
    image: nethermind/nethermind:$NETHERMIND_VERSION
    container_name: nethermind
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --config=none.cfg
      --Init.ChainSpecPath=/configs/chainspec.json
      --Init.GenesisHash=$GENESIS_HASH
      --Init.BaseDbPath=/execution_data
      --Sync.SnapSync=true
      --JsonRpc.Host=localhost
      --JsonRpc.Port=8551
      --JsonRpc.Enabled=true
      --JsonRpc.EnabledModules=["eth","web3","net","engine"]
      --JsonRpc.JwtSecretFile=/configs/jwt.hex
      --Discovery.Bootnodes=$EXECUTION_BOOTSTRAP_NODE_1,$EXECUTION_BOOTSTRAP_NODE_2
      --Merge.Enabled=true
      --KeyStore.KeyStoreDirectory=/execution_data/keystore
      --Network.MaxActivePeers=50
    
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"
  
  nimbus2_checkpoint:
    image: statusim/nimbus-eth2:multiarch-$NIMBUS2_VERSION
    container_name: nimbus2_checkpoint
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      trustedNodeSync
      --network=/configs
      --data-dir=/consensus_data
      --trusted-node-url=$CHECKPOINT_SYNC_URL

  nimbus2:
    image: statusim/nimbus-eth2:multiarch-$NIMBUS2_VERSION
    container_name: nimbus2
    depends_on:
      nimbus2_checkpoint:
        condition: service_completed_successfully
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    network_mode: host
    command: >
      --network=/configs
      --data-dir=/consensus_data
      --bootstrap-file=/configs/bootnodes.txt
      --genesis-state=/configs/genesis.ssz
      --jwt-secret=/configs/jwt.hex
      --el='http://127.0.0.1:8551'
      --nat=extip:$EXTERNAL_IP
      --rest
      --rest-address='127.0.0.1'
      --rest-port=5052
  
  # Note that nimbus doesn't support non-interactive keystore import,
  # please prepare the validator_data using the nimbus_beacon_node deposits import command.
  nimbus2_validator:
    image: statusim/nimbus-validator-client:multiarch-$NIMBUS2_VERSION
    container_name: nimbus2_validator
    depends_on:
      nimbus2:
        condition: service_started
    volumes:
      - $VALIDATOR_DATA_VOLUME:/validator_data
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    network_mode: host
    command: >
      nimbus_validator_client
      --data-dir=/validator_data
      --validators-dir=/validator_data/wallet/validators
      --secrets-dir=/validator_data/wallet/secrets
      --beacon-node=['127.0.0.1:5052']

