version: "3.8"
services:
  nethermind:
    image: "nethermind/nethermind:1.25.4"
    container_name: "nethermind"
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --datadir=/execution_data
      --baseDbPath=/execution_data
      
      --Init.ChainSpecPath=/configs/chainspec.json
      --EthStats.Enabled=true
      --EthStats.Name=${NODE_NAME}
      --EthStats.Secret=${ETH_STATS_SECRET}
      --EthStats.Server=${ETH_STATS_ADDRESS}

      --Hive.Enabled=true      
      --Hive.GenesisFilePath=/configs/genesis.json

    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"

  prysm_beacon:
    image: prysmaticlabs/prysm-beacon-chain:$PRYSM_BEACON_VERSION
    container_name: prysm_beacon
    depends_on:
      - nethermind
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --accept-terms-of-use
      --genesis-state=/configs/genesis.ssz
      --chain-config-file=/configs/config.yaml
      --datadir=/consensus_data
      --bootstrap-node $CONSENSUS_BOOTSTRAP_NODE_1,$CONSENSUS_BOOTSTRAP_NODE_2
      --execution-endpoint=http://localhost:8551
      --jwt-secret=/configs/jwt.hex
      --suggested-fee-recipient $FEE_RECIPIENT
      --min-sync-peers=0
      --monitoring-host 0.0.0.0
      --grpc-gateway-host 0.0.0.0
      --rpc-host 0.0.0.0
      --verbosity $PRYSM_VERBOSITY
      --p2p-max-peers 250
      --subscribe-all-subnets
      --minimum-peers-per-subnet 0
      --contract-deployment-block 0
      --block-batch-limit 512
      --block-batch-limit-burst-factor 10
      --p2p-host-ip $EXTERNAL_IP
      --checkpoint-sync-url=$CHECKPOINT_SYNC_URL
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"

