version: "3.8"

services:
  besu:
    image: hyperledger/besu:$BESU_VERSION
    container_name: besu
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --data-path=/execution_data
      --genesis-file=/configs/genesis.json
      --network-id=$LUKSO_MAINNET_NETWORK_ID
      --engine-jwt-secret=/configs/jwt.hex
      --nat-method=DOCKER
      --p2p-host="$EXTERNAL_IP"
      --rpc-http-enabled
      --rpc-http-host="0.0.0.0"
      --rpc-http-apis="ETH,NET"
      --rpc-http-cors-origins="*"
      --bootnodes="$EXECUTION_BOOTSTRAP_NODE_1,$EXECUTION_BOOTSTRAP_NODE_2"
      --metrics-enabled
      --metrics-host="0.0.0.0"
      --ethstats="${NODE_NAME}:${ETH_STATS_SECRET}@${ETH_STATS_ADDRESS}"

    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"

  lighthouse:
    image: sigp/lighthouse:$LIGHTHOUSE_VERSION
    restart: unless-stopped
    depends_on:
      - geth
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
      - $CONFIGS_VOLUME/lighthouse/deploy_block.txt:/configs/shared/deploy_block.txt
    command:
      - lighthouse
      - --testnet-dir=/configs/shared
      - bn
      - --datadir=/consensus_data
      - --listen-address=0.0.0.0
      - --eth1
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --discovery-port=9000
      - --enable-private-discovery
      - --enr-address=$EXTERNAL_IP
      - --execution-jwt=/configs/jwt.hex
      - --execution-endpoint=http://localhost:8551
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --suggested-fee-recipient=$FEE_RECIPIENT
      - --boot-nodes=$CONSENSUS_BOOT_NODES
      - --slots-per-restore-point=32
    network_mode: host